# Generated by Django 4.1.4 on 2023-08-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_blog_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='excert',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='explain',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='pic1',
            field=models.ImageField(blank=True, default='noimagep.jpg', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='blog',
            name='pic2',
            field=models.ImageField(blank=True, default='noimagep.jpg', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='blog',
            name='quotes',
            field=models.TextField(default=''),
        ),
    ]
