# Generated by Django 4.1.4 on 2023-08-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_brandservices_mainservices_subservices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='seller',
            field=models.CharField(default='Moonarty', max_length=500),
        ),
    ]
