# Generated by Django 4.1.4 on 2023-09-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_services_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Done')], default=1),
        ),
    ]
