# Generated by Django 4.1.4 on 2023-09-06 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_seller_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='status',
        ),
    ]
